import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Common.module.scss";
import Button from "@material-ui/core/Button";
import Link from "next/link";
import Navbar from "./components/Navbar";
import Home from "./src/home/Home";
import Contact from "./src/contact/Contact";


export default function App() {
  return (
    <div className={styles.container}>
      <Head style={styles.head_wrapper}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <Home />
      </main>
      <footer className={styles.footer_wrapper}>
        <Contact />
      </footer>
    </div>
  );
}
